#!/usr/bin/python
import subprocess
import sys
objdump_args = ['objdump', '-h', '-w', sys.argv[1]]
objdump_proc = subprocess.Popen(objdump_args, stdout=subprocess.PIPE)
objdump_stdout = objdump_proc.communicate()[0]
if objdump_proc.returncode != 0:
    sys.exit('Could not dump %s' % filename)
size = None
offset = None
for line in objdump_stdout.splitlines():
    fields = line.split()
    if len(fields) <= 7:
        continue
    if fields[1] != ".note.llvm":
        continue
    try:
        idx = int(fields[0])
        size = int(fields[2], 16)
        offset = int(fields[5], 16)
        break
    except ValueError:
        continue

if offset is None:
   sys.exit("Failed to find the .note.llvm section.")

with open(sys.argv[1]) as f:
    f.seek(offset)
    c = f.read(size)
with open(sys.argv[1] + ".llvm", "w") as f:
    f.write(c)
