#!/usr/bin/python
import sys
import subprocess

gcc_retcode = subprocess.call(["/usr/bin/gcc"] + sys.argv[1:])
if gcc_retcode != 0:
    sys.exit(gcc_retcode)

clang_retcode = subprocess.call(["/usr/bin/clang"] + sys.argv[1:])
sys.exit(gcc_retcode)
